<?php
    //Include the PHP functions to be used on the page 
    include('common.php'); 
	
    //Output header and navigation 
    outputHeader("Trex Game - Leaderboard");
    outputBannerNavigation("Leaderboard");
?>

<script type="text/javascript" src="../js/leaderboardScript.js"></script>

<!-- Table is generated by leaderboardScript.js using javascript -->

<?php
    //Output the footer
    outputFooter();
?>